### ISSUE TITLE
Phasor Plot Error

### ISSUE THREAD

**Issue by jrapaka1** [zoccoler/napari-flim-phasor-plotter#57]
I am encountering a major error in my phasor plot when I use the flim-phasor-plotter plugin. I used the napari-sdtfile plugin to upload my sdt file into napari, then used the phasor plotter plugin. Here is the plot I got:
![NapariPhasorPlot](https://github.com/zoccoler/napari-flim-phasor-plotter/assets/171189705/89ef8108-2f3b-4caf-8fb4-b76ed7e34075)

I have tried uploading the file in .tif format as well, and I get a very similar looking phasor plot. Any ideas about how to troubleshoot this error?

**Comment by zoccoler** [comment]
Hi @jrapaka1 ,

I am not sure what should be the correct phasor plot for your data, but it could be that the plugin expects the images to have a specific shape standard in order to work: (ut, t, z, y, x) where ut is the flim dimension.

If for example you don't have a z dimension in your data, there should still be a unitary z-axis (for example, (140, 1, 1, 256, 256) ).

If you used another plugin to load your data, your image shape and dimensions may be completely different and so the plugin would process them wrongly.

**Comment by zoccoler** [comment]
Closed via #59
